### ISSUE TITLE
No error message when user uploads the translated tokens a second time

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#117]
If user try to upload a translated token set a second time, the server will return an error:
'{"success":false, "message":"No Changes. Existing token is already up-to-date."}'

However no message is shown on the user's screen. This will leave the user clueless on what's happening.

**Comment by HimanshuBCS** [comment]
I have implement code for the No error message when user uploads the translated tokens second time.
![uploadtokenserrormessage2](https://user-images.githubusercontent.com/26620717/28762968-4c3b5654-75d8-11e7-9444-7b8209085547.png)
![uploadtokenserrormessage](https://user-images.githubusercontent.com/26620717/28762969-4c644c58-75d8-11e7-984f-248af8d9a3c6.png)
