### ISSUE TITLE
The new update breaks "download tokens"

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#138]
After the new update, I can no longer download tokens for any combinations except for Khandesi OA-KHN-NT. 

The issue is, UI is sending OA-KHN-NT is as the version, regardless of the version choose by the user. The downloaded token file has the name HindiOA-KHN-NTPhilemonTokens.xlsx.

Kindly fix this asap.

**Comment by HimanshuBCS** [comment]
I have checked at our end & I am able to download token after selecting specific version, language.
