### ISSUE TITLE
Not Found Component  added 

### ISSUE THREAD

**Issue by HimanshuBCS** [friendsofagape/mt2414ui#160]
I have added not found page, when use enter the wrong path in URL then rendered 404 page not found at client side.

**Comment by beniza** [comment]
that's good. We should make a custom 404 page...

**Comment by HimanshuBCS** [comment]
Currently I have added this one, PFA screenshot for the same.
![notfound](https://user-images.githubusercontent.com/26620717/30260732-c29990c0-96e6-11e7-9524-d51bca32995d.png)

**Comment by HimanshuBCS** [comment]
Yes, I have used the same image.

**Comment by beniza** [comment]
(y)
