### ISSUE TITLE
Improvement in Translation Page.

### ISSUE THREAD

**Issue by HimanshuBCS** [friendsofagape/mt2414ui#165]
Need to improve UI for the translation below points:
**1.** After the language, version and revision numbers are selected the books list drops down but remains there even after we select the generate token, there should be a way to hide/unhide this option as the we need to scroll down the page to view concordance.
**2.** There is a token text box above the concordance which is empty the entire time. Ideally when we select the token from the list box on the left, it should display in that box.
**3.** The concordance does not highlight the word for which the concordance has been generated. Let me know if I need to place a tag next to the token in the concordance text.
**4.** Refresh button must be above the concordance box and not below it.

**Comment by faithfulmaster** [comment]
Done
