### ISSUE TITLE
Create "Upload Sources"

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#2]
Create a page for the user to submit the Source documents

### Requirements
1. Endpoint: https://api.mt2414.in/v1/sources
1. Payloads
    1. **language** [Ethnologue code of the language]
    1. **content** [Content of all the source documents stored]
    1. **Access ID** and **Key** [Returned as a response after authentication]

#### curl
$ curl -X POST http://127.0.0.1:8000/v1/sources -d '{"language":"XYZ", "content":{"GEN":"\\id GEN\n\\c 1\n\\p\n\\v 1 In the beginning God created the heavens and the earth.\n\\v 2 And the earth was without form and was void form.", "EXO":"\\id EXO\n\\c 1\n\\p\n\\v 1 Now these are the names of the children of Israel, which came to Egypt; every man and his household came with Jacob\n\\v 2 Reuben, Simeon, Levi, and Judah", "LEV":"\\id LEV\n\\c 1\n\\p\n\\v 1 And the Lord called unto Moses, and spake unto him out of the tabernacle of the congregation, saying,\n\\v 2 Speak unto the children of Israel"}}' -H "Authorization:bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaWpvYjg5QGdtYWlsLmNvbSJ9.RX_rx24v1uhzRv5FypR1X7QlyALUPvHSg1q6OUFtGos"

   Response: {}

![sources](https://cloud.githubusercontent.com/assets/4908971/24288260/aa5dda18-10a2-11e7-9f36-190bd9d18d66.png)

### Logic
```
bibContent = '{"language":"<ethnologue_code>", "content":'

for file in file_list_selected_by_the_user:

    file_content=<read the content of the file>

    book_id = re.search("\\id (.{3}), file_content, re.U) # <To find the value of the \id tag in the current file>  This is a 3 letter code in uppercase, normally appear as the first line of the book"

    bibContent += '{"book_id.group(1)":"file_content"},'

bibContent += "}'"
```

**Comment by udkumar** [comment]
@beniza Curl URL will be "https://api.mt2414.in/v1/sources" right?

**Comment by bijob89** [comment]
yes.. you're right

**Comment by HimanshuBCS** [comment]
Now source page is completed , Kindly review and confirm for the same.
