### ISSUE TITLE
UI Translation

### ISSUE THREAD

**Issue by HimanshuBCS** [friendsofagape/mt2414ui#21]
I have completed UI for the task to generate concordance for the particular tokens in UI. 
Also find attached screenshot for the same.
![ui](https://user-images.githubusercontent.com/26620717/27080473-a7da78b8-5059-11e7-936c-cff4f4afe6f1.png)

**Comment by HimanshuBCS** [comment]
Done.

**Comment by faithfulmaster** [comment]
Can be first implemented on Desktop version of AutographaMT
