### ISSUE TITLE
Save downloaded items to a user specified location

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#24]
Currently the items downloaded are directly being saved in the default location (downloads folder). We must give the user the ability (File-Open Dialogue Box) to save the files to his preferred location.

**Comment by HimanshuBCS** [comment]
Ok I'll do for the same.

**Comment by beniza** [comment]
Provide instructions to the user on how to save the downloaded tokens to a desired location. 
## Chrome

## Firefox

**Comment by faithfulmaster** [comment]
This feature is not recommended by Internet communities, nor do latest browsers support this.
