### ISSUE TITLE
Byte Order Mark is missing when downloading tokens

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#35]
The Byte Order Mark (BOM) is missing in the downloaded tokens file.

#### Background Information
The UTF-8 BOM is a sequence of bytes (EF BB BF) that allows the reader to identify a file as being encoded in UTF-8. If it is missing in a file, some programs will not be able to display the text correctly. 
##### With BOM
  माझे, येशूचा 
##### Without BOM
  à¤®à¤¾à¤à¥‡, 
  à¤¯à¥‡à¤¶à¥‚à¤šà¤¾, 

[Read more about BOM here](https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom)

**Comment by beniza** [comment]
In Python you can achieve this by the following code. Node/ReactJS should have something similar....
import codecs
f.write(codecs.BOM_UTF16_LE)

**Comment by HimanshuBCS** [comment]
I have added UTF-8 BOM for download tokens for the same.
Result will be reflected on the server after deploying the build.

**Comment by HimanshuBCS** [comment]
Ready for the review.
