### ISSUE TITLE
Download tokens as XLS

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#36]
When we download the tokens, the file downloaded is a .xls extension. However the file is a plain text file. Please download the file as a proper .xls file.

### Tip
There may be existing libraries that can convert a plain text file into a .xls file.

**Comment by HimanshuBCS** [comment]
Ok. I'll do for the same.

**Comment by HimanshuBCS** [comment]
But right now download tokens is already in the .xls format.
![xls format](https://user-images.githubusercontent.com/26620717/27272777-968c2004-54e9-11e7-951d-e25de5836bc9.png)

**Comment by HimanshuBCS** [comment]
Done.

**Comment by beniza** [comment]
Could you push it to the server? Will Uday be able to review the code?

**Comment by HimanshuBCS** [comment]
Yes I have the pushed the updated code to the server.
