### ISSUE TITLE
Display links for the APIs only after a successful login

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#38]
Autographa MT permits people to access the resources without login to the system. Please fix this urgently. Make sure that the links to various tools are available only when the user is logged in. 

### Tip
Hiding the menu item is not the right solution. The system shouldn't create these links until the user logs in.

**Comment by HimanshuBCS** [comment]
Done.

**Comment by beniza** [comment]
Himanshu,

I get the following error on the server now

[image: Inline image 1]

Benjamin
