### ISSUE TITLE
Add forgot password recovery link on the sign in page

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#41]
API is already ready

**Comment by HimanshuBCS** [comment]
Need to be CURL for the same.

**Comment by beniza** [comment]
Bijo will give the CURL once the API is ready

**Comment by HimanshuBCS** [comment]
Got it & try to implement for the same asap.

**Comment by HimanshuBCS** [comment]
I have commit the updated code in my repo for forgot password & dummy page for reset password. So you have to make an API at your end for reset password(http://localhost:3000/forgotpassword)

**Comment by HimanshuBCS** [comment]
Done & changes will be reflected after server deploy.
