### ISSUE TITLE
Display Book Names in places of Book Codes 

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#43]
On several places on the site Book Codes are given. Most end users are not familiar with Book codes. So we should change the book code to book names. In the future we will have to provide the book names in the Gateway languages (using a skin).

**Comment by HimanshuBCS** [comment]
Added the book name. Result will be reflect on server after deploy build.
Also I have committed the updated code. 
![download wordlist bookname](https://user-images.githubusercontent.com/26620717/27684374-6a42a292-5ce7-11e7-811f-6fa855c65498.png)

![download wordlist exlude](https://user-images.githubusercontent.com/26620717/27684410-82dc0e9c-5ce7-11e7-9d86-da03ce076196.png)
