### ISSUE TITLE
Option to create a new target language

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#45]
Currently there is no option for the user to specify to which language he is translating into. Please provide a way to add a new language as a target language.

**Comment by beniza** [comment]
Server operations: [Suggestion]
If the language exists on the server and the user is requesting for a new book, send the tokens of the new books

If the language is on the server and the user is requesting for the tokens of the language that has at least some translated tokens available, send them the remaining tokens (or send them the tokens, but with translations wherever it is available)

Finally if the language and the entire token set for the book is available on the server, report to the user that the book is already translated and (optionally) take user to the download draft page

If the user wanted to force download the tokens of an existing book (NEW USER STORY: update the translation of an existing token set), then we could provide the full token set of the book.

**Comment by HimanshuBCS** [comment]
Done.
