### ISSUE TITLE
Convert source selection text boxes into combo boxes

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414ui#48]
Currently, except for the language, information such as Version and Revision is entered via a text box. It requires that a user need to have an information about the languages already available to him. By changing these text boxes into combo boxes and populating them from the table with the existing information (filtered according to the previous choice made by the user) he will be able to make the right decisions fast.

**Comment by HimanshuBCS** [comment]
Working on the Remember User States
I have completed task for the source language(User States).
When a user select a combination of source, the system should remember it across the pages (until the user changes it to something else).
Currently working on the Version(User States).

**Comment by HimanshuBCS** [comment]
I have completed the task for the Source Language, Version, Revision & getting the list of books corresponding.
Initially when the page open come with option **Choose**  Source Language, Version, Revision & get list of the books.

**Comment by HimanshuBCS** [comment]
Also I have commit & push the updated code for the same on repo.
Changes will be reflect on live server after deploy build.
