### ISSUE TITLE
Get languages and Books

### ISSUE THREAD

**Issue by faithfulmaster** [friendsofagape/mt2414ui#8]
After signing in, on page load, display the list of languages, their versions, alogwith the list of books and revision numbers, available in the system. This page will give the user a tabular view of the items that are available in the database.

**Comment by HimanshuBCS** [comment]
Now after signing, on page load, display the **list of languages, their versions** successfully.  Also find the screen-shot for the same.
![get languages and books 8](https://cloud.githubusercontent.com/assets/26620717/26772028/a4d37fa4-49e0-11e7-9217-212f3292d2f3.png)

But we are getting the error for the **list of books and revision number**. So trying to resolve earliest at our end for the same.
