### ISSUE TITLE
Super Admin page

### ISSUE THREAD

**Issue by HimanshuBCS** [friendsofagape/mt2414ui#85]
Super Admin page: This will be visible only to the super admin where it will list all the user emails registered with AutographaMt. It will have one check box called Admin. When the check box is selected an API call must be made to server. This will update the user privilege ie admin or member.
So When a user logs in the access token and the user privilege will be provided in the response as {"access_token":"<Access token>","role":"<role>"}
*The different roles would be 
1. superadmin
2. admin
3. member

**Comment by faithfulmaster** [comment]
Done
