### ISSUE TITLE
Upload Tokens

### ISSUE THREAD

**Issue by faithfulmaster** [friendsofagape/mt2414ui#9]
Upload the list of translated tokens (xlsx file) for a particular language

**Comment by HimanshuBCS** [comment]
Upload tokens no successfully completed & ready for the review. When we upload tokens using XLS file getting success message in UI **Token translations have been updated.**  . Also find below screen shot for the same.
![upload tokens done](https://cloud.githubusercontent.com/assets/26620717/26771850/77ab8d60-49df-11e7-8ac1-0821c12adaac.png)
