### ISSUE TITLE
Development for Creating sources

### ISSUE THREAD

**Issue by HimanshuBCS** [friendsofagape/mt2414ui#97]

**Comment by HimanshuBCS** [comment]
Need to create an API to return the language and version so that you can display in the drop down menu

**Comment by beniza** [comment]
the /v1/getlanguages api does it. Bijo please confirm

**Comment by HimanshuBCS** [comment]
Create source page Done
Before 

![createsource_before_create_source](https://user-images.githubusercontent.com/26620717/28314760-6dc22ea0-6bd9-11e7-9a2d-44c8f2471a23.png)

After  
![createsource_after_create_source](https://user-images.githubusercontent.com/26620717/28314772-7826d292-6bd9-11e7-9143-4d8966237512.png)
